# équivalent du fichier .env
spring.application.name=microcommerce
server.port=8081

# Configuration MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/microcommerce
spring.data.mongodb.database=microcommerce

# Configuration MongoDB (optionnel)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG